"""QntySpot -- deterministic policy-bound spot runtime.

PHASE: INK V0F / HUMAN-SIGNED EXECUTION SOURCE CEILING / PRE-GRANT
--------------------------------------------------------------------------
This package contains the merged bounded Ink and Solana/Jupiter adapters and
one bounded Robinhood/Chainlink/0x adapter. It has no signer and no key
handling. The reviewed Ink V0F source ceiling is HUMAN_SIGNED_EXECUTION:
a matching external grant may authorize the bounded envelope/approval/exact
externally-signed-byte path. No production Level-3 grant is provisioned by
this source transition, so production live-capital authority remains absent.

``execution_contract`` and ``ledger.execution_schema`` are the frozen Program B
pre-live execution contract. ``ledger.execution`` is the offline B1 runtime;
``authority_root`` is the external-root contract consumer. Together they
provide immutable records, deterministic validators, and a SQLite authority
surface. They authorize no Level-1+ runtime behavior without a current exact
external grant. The runtime source ceiling is Level 3, while signature
production remains denied because PRODUCE_SIGNATURE exists only at Level 4.

What it does contain: an immutable domain model, a strict fail-closed policy
reader, a deterministic economic-limit contract, an append-only SQLite ledger
with database-enforced exactly-once economic identity and atomic budget
reservation, deterministic replay, and restart recovery that never retries an
action whose outcome is unknown.

See ``docs/AUTHORITY.md`` for the binding statement of what this phase
authorizes and forbids.
"""

from __future__ import annotations

__version__ = "0.0.1a0"

#: Machine-readable phase marker. The source ceiling is Level 3, but every
#: Level-1+ runtime action still requires a current exact external grant.
#: SIGNING_AUTHORIZED means QntySpot may produce a signature; it remains false.
#: No production Level-3 grant is provisioned by this source transition.
AUTHORITY = "INK_V0F_HUMAN_SIGNED_EXECUTION_PREGRANT"
NETWORK_AUTHORIZED = True
SIGNING_AUTHORIZED = False
LIVE_CAPITAL_AUTHORIZED = False

from .errors import (  # noqa: E402
    BudgetExceededError,
    BackupAliasError,
    BackupDestinationError,
    BackupError,
    BackupInterruptedError,
    BackupVerificationError,
    CanonicalFormError,
    DatabaseIntegrityError,
    DatabaseMalformedError,
    DatabaseMissingError,
    DatabaseOperationError,
    DatabaseSchemaError,
    DuplicateEconomicActionError,
    IdentityError,
    LedgerError,
    PolicyError,
    PolicyMissingError,
    QntySpotError,
    LockError,
    LockHeldError,
    LockPathError,
    OperationsError,
    ReplayDivergenceError,
    InkError,
    RpcError,
    RpcProtocolError,
    RpcResponseTooLargeError,
    RpcTimeoutError,
    RpcTransportError,
    SafeHaltError,
    StateTransitionError,
    SolanaError,
    SolanaTransportError,
    SolanaTimeoutError,
    SolanaResponseTooLargeError,
    SolanaProtocolError,
    JupiterApiError,
    RobinhoodError,
    RobinhoodTransportError,
    RobinhoodProtocolError,
    ZeroXApiError,
    ZeroXApiKeyRequired,
    ApprovalContractError,
    AuthorityCeilingError,
    ChainTruthError,
    EnvelopeValidationError,
    ExecutionContractError,
    SessionIdentityError,
    AuthorityVerificationError,
)
from .domain import (  # noqa: E402
    CycleV0,
    EconomicBounds,
    ExecutionPlanV0,
    FillReceiptV0,
    IntentV0,
    LadderKind,
    LadderLevelV0,
    LadderV0,
    PolicyV0,
    PortfolioBudgetV0,
    QuoteV0,
    RuntimeStateV0,
    Side,
    economic_action_id,
)
from .identity import (  # noqa: E402
    AssetClass,
    EvmInstrumentRef,
    InstrumentV0,
    SolanaCluster,
    SolanaInstrumentRef,
    TokenProgram,
)
from .execution_contract import (  # noqa: E402
    CONTRACT_VERSION as PROGRAM_B_CONTRACT_VERSION,
    PHASE_GRANTED_AUTHORITY_LEVEL,
    ApprovalActionV0,
    AuthorityLevel,
    AuthorityPolicyRefV0,
    Capability,
    ChainObservationV0,
    ChainTruthV0,
    ChainTruthVerdict,
    EconomicActionIDV0,
    ExecutionEnvelopeV0,
    ExecutionReadiness,
    ExecutionSessionV0,
    ExternalTransactionReferenceV0,
    FinalityPolicyV0,
    SignedTransactionRecordV0,
    SubmissionAttemptV0,
)
from .exact_signed_bytes import (  # noqa: E402
    ExactSignedBytesAdmissionV0,
    ExactSignedBytesScopeV0,
    ExactSignedBytesTransport,
    ExactSignedTransactionRecordV0,
    JsonRpcExactSignedBytesTransport,
    ParsedExactSignedBytesV0,
    ValidatedExactSignedBytesV0,
    validate_exact_signed_bytes,
)
from .ink_v0f_execution import (  # noqa: E402
    INK_V0F_ROUTER_ADDRESS,
    INK_V0F_ROUTER_ARTIFACT_DIGEST,
    INK_V0F_ROUTER_BYTECODE_SHA256,
    InkV0FApprovalCallV0,
    InkV0FHumanSigningPreviewV0,
    InkV0FRouterIdentityV0,
    InkV0FSwapCallV0,
    amount_out_min_atomic,
    assert_ink_v0f_exit_admissible,
    build_ink_v0f_human_signing_preview,
    consume_ink_v0f_router_artifact,
    decode_approve,
    decode_swap_exact_tokens_for_tokens,
    encode_approve,
    encode_swap_exact_tokens_for_tokens,
)
from .ink_v0f_preauth import (  # noqa: E402
    ALLOWANCE_OBSERVATION_SCHEMA,
    ERC20_ALLOWANCE_SELECTOR,
    ROUTER_FACTORY_SELECTOR,
    ROUTER_OBSERVATION_SCHEMA,
    ROUTER_WETH_SELECTOR,
    InkV0FAllowanceObservationV0,
    InkV0FLiveVerifier,
    InkV0FRouterObservationV0,
    assert_ink_v0f_approval_admissible,
    assert_ink_v0f_execution_envelope_admissible,
    build_ink_v0f_approval_action,
    build_ink_v0f_execution_envelope,
)
from .authority_root import (  # noqa: E402
    AUTHORITY_ROOT_CONTRACT_VERSION,
    AuthorityGrantReceiptV0,
    AuthorityIssuancePolicyV0,
    TrustedAuthorityRootV0,
    VerifiedAuthorityGrantV0,
    effective_authority_level,
    effective_capabilities,
    effective_capital_ceilings,
    assert_effective_capital_within,
    load_trusted_authority_root,
    assert_issuance_request_admissible,
    verify_authority_grant,
)
from .policy import load_policy_file, load_policy_text, parse_policy  # noqa: E402
from .states import IntentState  # noqa: E402
from .solana import (  # noqa: E402
    JupiterV2Client,
    SolanaMarketObservationV0,
    SolanaRpcClient,
    SolanaShadowAdapter,
)

__all__ = [
    "__version__",
    "AUTHORITY",
    "NETWORK_AUTHORIZED",
    "SIGNING_AUTHORIZED",
    "LIVE_CAPITAL_AUTHORIZED",
    "QntySpotError",
    "CanonicalFormError",
    "PolicyError",
    "PolicyMissingError",
    "IdentityError",
    "StateTransitionError",
    "LedgerError",
    "DuplicateEconomicActionError",
    "BudgetExceededError",
    "OperationsError",
    "LockError",
    "LockHeldError",
    "LockPathError",
    "DatabaseOperationError",
    "DatabaseMissingError",
    "DatabaseMalformedError",
    "DatabaseIntegrityError",
    "DatabaseSchemaError",
    "BackupError",
    "BackupAliasError",
    "BackupDestinationError",
    "BackupInterruptedError",
    "BackupVerificationError",
    "ReplayDivergenceError",
    "SafeHaltError",
    "InkError",
    "RpcError",
    "RpcProtocolError",
    "RpcResponseTooLargeError",
    "RpcTimeoutError",
    "RpcTransportError",
    "SolanaError",
    "SolanaTransportError",
    "SolanaTimeoutError",
    "SolanaResponseTooLargeError",
    "SolanaProtocolError",
    "JupiterApiError",
    "RobinhoodError",
    "RobinhoodTransportError",
    "RobinhoodProtocolError",
    "ZeroXApiError",
    "ZeroXApiKeyRequired",
    "ExecutionContractError",
    "AuthorityCeilingError",
    "SessionIdentityError",
    "EnvelopeValidationError",
    "ApprovalContractError",
    "ChainTruthError",
    "AuthorityVerificationError",
    "Side",
    "LadderKind",
    "LadderLevelV0",
    "LadderV0",
    "PolicyV0",
    "PortfolioBudgetV0",
    "CycleV0",
    "EconomicBounds",
    "IntentV0",
    "QuoteV0",
    "ExecutionPlanV0",
    "FillReceiptV0",
    "RuntimeStateV0",
    "economic_action_id",
    "AssetClass",
    "InstrumentV0",
    "EvmInstrumentRef",
    "SolanaInstrumentRef",
    "SolanaCluster",
    "TokenProgram",
    "IntentState",
    "PROGRAM_B_CONTRACT_VERSION",
    "PHASE_GRANTED_AUTHORITY_LEVEL",
    "AuthorityLevel",
    "Capability",
    "AuthorityPolicyRefV0",
    "ExecutionSessionV0",
    "ExternalTransactionReferenceV0",
    "ExecutionEnvelopeV0",
    "ApprovalActionV0",
    "SignedTransactionRecordV0",
    "SubmissionAttemptV0",
    "ExactSignedBytesAdmissionV0",
    "ExactSignedBytesScopeV0",
    "ExactSignedBytesTransport",
    "ExactSignedTransactionRecordV0",
    "JsonRpcExactSignedBytesTransport",
    "ParsedExactSignedBytesV0",
    "ValidatedExactSignedBytesV0",
    "validate_exact_signed_bytes",
    "INK_V0F_ROUTER_ADDRESS",
    "INK_V0F_ROUTER_ARTIFACT_DIGEST",
    "INK_V0F_ROUTER_BYTECODE_SHA256",
    "InkV0FApprovalCallV0",
    "InkV0FHumanSigningPreviewV0",
    "InkV0FRouterIdentityV0",
    "InkV0FSwapCallV0",
    "amount_out_min_atomic",
    "assert_ink_v0f_exit_admissible",
    "build_ink_v0f_human_signing_preview",
    "consume_ink_v0f_router_artifact",
    "decode_approve",
    "decode_swap_exact_tokens_for_tokens",
    "encode_approve",
    "encode_swap_exact_tokens_for_tokens",
    "ALLOWANCE_OBSERVATION_SCHEMA",
    "ERC20_ALLOWANCE_SELECTOR",
    "ROUTER_FACTORY_SELECTOR",
    "ROUTER_OBSERVATION_SCHEMA",
    "ROUTER_WETH_SELECTOR",
    "InkV0FAllowanceObservationV0",
    "InkV0FLiveVerifier",
    "InkV0FRouterObservationV0",
    "assert_ink_v0f_approval_admissible",
    "assert_ink_v0f_execution_envelope_admissible",
    "build_ink_v0f_approval_action",
    "build_ink_v0f_execution_envelope",
    "AUTHORITY_ROOT_CONTRACT_VERSION",
    "TrustedAuthorityRootV0",
    "AuthorityGrantReceiptV0",
    "AuthorityIssuancePolicyV0",
    "VerifiedAuthorityGrantV0",
    "load_trusted_authority_root",
    "assert_issuance_request_admissible",
    "verify_authority_grant",
    "effective_authority_level",
    "effective_capabilities",
    "effective_capital_ceilings",
    "assert_effective_capital_within",
    "ChainObservationV0",
    "ChainTruthV0",
    "ChainTruthVerdict",
    "EconomicActionIDV0",
    "FinalityPolicyV0",
    "ExecutionReadiness",
    "SolanaRpcClient",
    "JupiterV2Client",
    "SolanaMarketObservationV0",
    "SolanaShadowAdapter",
    "parse_policy",
    "load_policy_text",
    "load_policy_file",
]
